#!/usr/bin/env python3
"""Inline every player source into a single self-contained dist/index.html.

Usage: python3 build.py [week-file.json]
"""
import hashlib
import json
import pathlib
import re
import struct
import sys
import zlib

ROOT = pathlib.Path(__file__).parent
SRC = ROOT / "src" / "player"

# Strict dependency order. Nothing may import "upward" in this list.
MODULE_ORDER = [
    "parser.js", "machine.js", "storage.js", "effects.js",
    "render.js", "input.js", "editor.js", "main.js",
]

IMPORT_RE = re.compile(r"^[ \t]*import\s[^\n]*\n?", re.M)
EXPORT_RE = re.compile(r"^export\s+(?=(?:async\s+)?(?:function|const|let|class)\b)", re.M)
BAD_EXPORT_RE = re.compile(r"^export\s+(?:default\b|\{)", re.M)
PLACEHOLDER_RE = re.compile(r"<!--INLINE:\w+-->")


def read_module(name: str) -> str:
    """Strip module syntax so the file can be concatenated into one script."""
    path = SRC / name
    text = path.read_text(encoding="utf-8")

    if BAD_EXPORT_RE.search(text):
        sys.exit(f"{name}: `export default` and `export {{ ... }}` are unsupported; "
                 f"use `export function` / `export const` / `export class`")

    for match in IMPORT_RE.finditer(text):
        line = match.group(0).strip()
        if "./" not in line:
            sys.exit(f"{name}: only sibling imports are allowed, found: {line}")

    text = EXPORT_RE.sub("", IMPORT_RE.sub("", text))
    return f"/* ---------- {name} ---------- */\n{text.strip()}\n"


# A "?" drawn as a coarse mask, scaled up. Keeps the icon dependency-free.
GLYPH = [
    " ####### ",
    "###   ###",
    "##     ##",
    "       ##",
    "      ## ",
    "    ###  ",
    "   ##    ",
    "   ##    ",
    "   ##    ",
    "         ",
    "   ##    ",
    "   ##    ",
]

GROUND = (43, 52, 68)     # matches the slate palette
INK = (255, 196, 77)      # matches the accent


def write_png(path: pathlib.Path, size: int = 180) -> None:
    """Emit a flat icon with a scaled '?' glyph, using only the stdlib."""
    scale = 12
    glyph_w = len(GLYPH[0]) * scale
    glyph_h = len(GLYPH) * scale
    off_x = (size - glyph_w) // 2
    off_y = (size - glyph_h) // 2

    rows = []
    for y in range(size):
        row = bytearray()
        gy = (y - off_y) // scale
        for x in range(size):
            gx = (x - off_x) // scale
            on = (0 <= gy < len(GLYPH) and 0 <= gx < len(GLYPH[0])
                  and GLYPH[gy][gx] == "#")
            row += bytes(INK if on else GROUND)
        rows.append(bytes(row))

    raw = b"".join(b"\x00" + row for row in rows)

    def chunk(tag: bytes, data: bytes) -> bytes:
        body = tag + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)

    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 2, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(raw, 9))
        + chunk(b"IEND", b"")
    )


SERVICE_WORKER = """\
// Generated by build.py. The cache name is derived from the page contents, so
// publishing a new build invalidates the old one instead of serving it forever.
const CACHE = "bible-clue-{version}";
const ASSETS = ["./", "./index.html", "./icon-180.png"];

self.addEventListener("install", event => {{
  event.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
}});

self.addEventListener("activate", event => {{
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
}});

self.addEventListener("fetch", event => {{
  if (event.request.method !== "GET") return;
  event.respondWith(
    fetch(event.request)
      .then(response => {{
        const copy = response.clone();
        caches.open(CACHE).then(c => c.put(event.request, copy));
        return response;
      }})
      .catch(() => caches.match(event.request).then(hit => hit || caches.match("./index.html")))
  );
}});
"""


def write_service_worker(path: pathlib.Path, html: str) -> None:
    version = hashlib.sha256(html.encode("utf-8")).hexdigest()[:8]
    path.write_text(SERVICE_WORKER.format(version=version), encoding="utf-8")


def main() -> None:
    week_name = sys.argv[1] if len(sys.argv) > 1 else "week-2026-09-13.json"
    week_path = ROOT / "src" / "data" / week_name
    if not week_path.exists():
        sys.exit(f"no such week file: {week_path}")

    week = json.loads(week_path.read_text(encoding="utf-8"))
    html = (SRC / "index.html").read_text(encoding="utf-8")
    css = (SRC / "style.css").read_text(encoding="utf-8")
    js = "\n".join(read_module(name) for name in MODULE_ORDER)

    if re.search(r"^[ \t]*(import|export)\s", js, re.M):
        sys.exit("module syntax survived inlining; check the source conventions")

    html = html.replace("<!--INLINE:css-->", f"<style>\n{css}\n</style>")
    html = html.replace("<!--INLINE:data-->", json.dumps(week, ensure_ascii=False, indent=2))
    html = html.replace("<!--INLINE:js-->", js)

    leftover = PLACEHOLDER_RE.search(html)
    if leftover:
        sys.exit(f"unreplaced placeholder: {leftover.group(0)}")

    out = ROOT / "dist" / "index.html"
    out.parent.mkdir(exist_ok=True)
    out.write_text(html, encoding="utf-8")
    write_service_worker(out.parent / "sw.js", html)
    write_png(out.parent / "icon-180.png")
    print(f"built {out.relative_to(ROOT)} ({len(html):,} bytes) from {week_path.name}")
    print("wrote dist/sw.js and dist/icon-180.png")


if __name__ == "__main__":
    main()
